### ISSUE TITLE
Variabel inladen van kolomnamen van src.manhole_maaiveld

### ISSUE THREAD

**Issue by arnoldvantveld** [Siebrand-HHD/OASDGLDatachecker#15]
De kolommen manh_id en maaiveld worden nu niet variabel ingeladen.
Dit zorgt ervoor dat als de tabel src.manhole_maaiveld veranderd, de code niet meer werkt. Deze kolommen toevoegen in de inifile

**Comment by Siebrand-HHD** [comment]
Wat is hier de status van?
In de checkresultaten-views, naar welke laag verwijs ik voor mijn (AHN3) maaiveld waardes?

**Comment by arnoldvantveld** [comment]
src.manhole_maaiveld voor de tabel.
{id_field} én {dem_field}
zie dit script:
https://github.com/Siebrand-HHD/OASDGLDatachecker/blob/bd137ad7b2bd085ddc8937ac35e3766e3b2abe76/tool_quality_checks/sql_checks.py#L346
